### ISSUE TITLE
This appears to have stopped working on our org repos

### ISSUE THREAD

**Issue by kevincowan** [SvanBoxel/delete-merged-branch#198]
Hi - I have deleted and reinstalled the bot but it is no longer deleted merged branches.  Is there anything else I should try.  Does it work OK if someone has enabled the Github setting to do the same.  I prefer the bot since it's easier to enable at org level. Thanks!

**Comment by SvanBoxel** [comment]
I can confirm I experienced this as well for some of my repos/orgs. I've scheduled some time later this week to debug the issue. Thanks for raising the issue.

**Comment by kevincowan** [comment]
Thanks for looking into it - much appreciated.  We are very grateful for your bot at ShopKeep.

**Comment by ted-prnd** [comment]
same issue

**Comment by SvanBoxel** [comment]
Should be fixed now. Could you confirm?

**Comment by SvanBoxel** [comment]
Closing as fixed. Please reopen if the issue persists.

**Comment by kevincowan** [comment]
Unfortunately this is still not working for us.  Is there anything I can do to help debug it.

**Comment by maciejqantas** [comment]
@SvanBoxel same in our case - branches still survive.
Should we try and reinstall?

**Comment by mogggggg** [comment]
Hey @SvanBoxel, this is also not working for repos in my org

**Comment by dmitrii-clarifai** [comment]
Same. Tried reinstall, didn't helped.

**Comment by danielbachhuber** [comment]
Still not working for us too. Thanks for your work on this though!

**Comment by jbrechtel** [comment]
Also not working for ours.

**Comment by SvanBoxel** [comment]
I'll start looking into this again tonight.

**Comment by SvanBoxel** [comment]
@danielbachhuber That surprises me. I've tested it [here](https://github.com/SvanBoxel/delete-test/pull/16) and the bot deletes the branch when it is merged. Could you perhaps send me the repo slug so I can check the debug logs?

**Comment by danielbachhuber** [comment]
@SvanBoxel Sure, the repo slug is `danielbachhuber/cedar`.

**Comment by maciejqantas** [comment]
still no luck on my end, branches still survive...
should I reinstall?
have you found anything in @danielbachhuber's logs?

**Comment by SvanBoxel** [comment]
@maciejqantas My bad, my deployment script was overwriting an env variable after x minutes causing it to fail (again). This is fixed now. Could you check again? Please share the repo slug if it is still failing.

**Comment by maciejqantas** [comment]
@SvanBoxel that fixed it :) I just merged a PR and the branch was deleted.
Thanks a lot for your work!

**Comment by rjmcneill** [comment]
@SvanBoxel working for us as well now, thanks very much for the quick fix! 🎉

**Comment by kevincowan** [comment]
Working for us too! Many thanks!
